version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:796973518232:task-definition/taskman-app-task"
        LoadBalancerInfo:
          ContainerName: "taskman-app"
          ContainerPort: 3000