Description: 'S3Gateway,ECRDocker,ECRApi,CloudWatchLogs and SecretsManager Endpoints'

Parameters:
  VpcId: { Type: String }
  PrivateRouteTableId: { Type: String }
  EndpointSecurityGroup: { Type: String }
  PrivateSubnetIds: { Type: CommaDelimitedList } 

Resources:
  # S3GatewayEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
  #     VpcId: !Ref VpcId
  #     RouteTableIds: [!Ref PrivateRouteTableId]
  #     VpcEndpointType: Gateway
  #     PolicyDocument:
  #       Statement: [{ Action: "s3:*", Effect: Allow, Principal: "*", Resource: "*" }]

  ECRDockerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      SecurityGroupIds: [!Ref EndpointSecurityGroup]
      SubnetIds: !Ref PrivateSubnetIds
      PrivateDnsEnabled: true

  ECRApiEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      SecurityGroupIds: [!Ref EndpointSecurityGroup]
      SubnetIds: !Ref PrivateSubnetIds
      PrivateDnsEnabled: true

  CloudWatchLogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      SecurityGroupIds: [!Ref EndpointSecurityGroup]
      SubnetIds: !Ref PrivateSubnetIds
      PrivateDnsEnabled: true

  # SecretsManagerEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     ServiceName: !Sub com.amazonaws.${AWS::Region}.secretsmanager
  #     VpcEndpointType: Interface
  #     VpcId: !Ref VpcId
  #     SecurityGroupIds: [!Ref EndpointSecurityGroup]
  #     SubnetIds: !Ref PrivateSubnetIds
  #     PrivateDnsEnabled: true

  DynamoDBEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.dynamodb"
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      SecurityGroupIds: [!Ref EndpointSecurityGroup]
      SubnetIds: !Ref PrivateSubnetIds
      PrivateDnsEnabled: true