Description: "EventBridge rule to trigger CodePipeline on ECR image push"
Parameters:
  ECRRepoArn: { Type: String }
  PipelineName: { Type: String }

Resources:
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Trigger pipeline on ECR image push
      EventPattern:
        source: ["aws.ecr"]
        detail-type: ["ECR Image Action"]
        detail:
          action-type: ["PUSH"]
          result: ["SUCCESS"]
          repository-name: 
            - !Select [1, !Split ['/', !Select [5, !Split [':', !Ref ECRRepoArn]]]] 
          image-tag: ["latest"] 

      Targets:
        - Arn: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}
          RoleArn: !GetAtt EventRole.Arn
          Id: codepipeline-trigger

  EventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: events.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokePipeline
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}

Outputs:
  EventRuleName:
    Value: !Ref EventRule