Description: 'AppsS3 and Artifacts Buckets'

Parameters:
  EnvironmentName: { Type: String }

Resources:
  AppS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub taskman-${EnvironmentName}-${AWS::AccountId}
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub codepipeline-artifacts-${EnvironmentName}-${AWS::AccountId}
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

Outputs:
  S3BucketName:
    Value: !Ref AppS3Bucket
  S3BucketArn:
    Value: !GetAtt AppS3Bucket.Arn
  ArtifactsBucketName:
    Value: !Ref ArtifactsBucket