Description: 'Endpoints, ALB, and Tasks Security Groups'   


Parameters:
  VpcId: { Type: String }
  ContainerPort: { Type: Number }
  VpcCidr: { Type: String, Default: '10.0.0.0/16'}

Resources:
  EndpointSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: VPC Endpoints Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VpcCidr

  AlbSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      

  TaskSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS Tasks Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref AlbSG

Outputs:
  EndpointSecurityGroup:
    Value: !Ref EndpointSG
  AlbSecurityGroup:
    Value: !Ref AlbSG
  TaskSecurityGroup:
    Value: !Ref TaskSG